name: restaurant-website
services:
  - name: web
    type: web
    ports:
      - port: 80
        protocol: http
    routes:
      - path: /
        protocol: http
    env:
      - name: NODE_ENV
        value: production
    build:
      builder: dockerfile
      dockerfile: Dockerfile
    scale:
      min: 1
      max: 3
    healthcheck:
      path: /health
      port: 80
      interval: 30s
      timeout: 10s
      retries: 3 